// Lists the calibrated cameras of an aiMotive recording, writes synchronised frames (and the masks) as PNG and
// optionally a run_vo rig of the opened cameras.
#include <chrono>
#include <cstdlib>
#include <exception>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include <boost/program_options.hpp>
#include <opencv2/imgcodecs.hpp>
#include <spdlog/spdlog.h>

#include <sdv/aimrec/recording.h>

namespace po = boost::program_options;
namespace fs = std::filesystem;

namespace {

// The rig reads the frames from the recording (aim_record), synchronised over the frame ids of the cameras a run
// selects; the camera YAMLs and masks are written out so that they can be inspected or edited.
void writeRig(const sdv::aimrec::Recording& rec, const fs::path& dir) {
  fs::create_directories(dir);
  std::ofstream rig(dir / "rig.yaml");
  rig << "# Generated by aimrec_extract\naim_record:\n  record: " << fs::absolute(rec.recordDir()).generic_string()
      << "\n  calibration: " << fs::absolute(rec.calibrationFile()).generic_string() << "\ncameras:\n";
  for (int c = 0; c < rec.size(); ++c) {
    const auto& cal = rec.calibration(c);
    std::ofstream cam(dir / (cal.label + ".yaml"));
    cam << fmt::format("# {} ({}), EUCM from the {} calibration\nwidth: {}\nheight: {}\nfx: {}\nfy: {}\ncx: {}\n"
                       "cy: {}\nalpha: {}\nbeta: {}\n",
                       cal.label, cal.deviceId, rec.vehicle(), cal.width, cal.height, cal.fx, cal.fy, cal.cx, cal.cy,
                       cal.alpha, cal.beta);
    if (!cal.mask.empty()) {
      cv::imwrite((dir / (cal.label + "_mask.png")).string(), cal.mask);
      cam << "mask: " << cal.label << "_mask.png\n";
    }
    const Eigen::Matrix3d R = cal.T_vehicle_camera.rotationMatrix();
    const Eigen::Vector3d t = cal.T_vehicle_camera.translation();
    rig << fmt::format("  - name: {}\n    camera: {}.yaml\n    T_body_camera:\n      translation: [{}, {}, {}]\n"
                       "      rotation_matrix: [{:.12f}, {:.12f}, {:.12f},\n"
                       "                        {:.12f}, {:.12f}, {:.12f},\n"
                       "                        {:.12f}, {:.12f}, {:.12f}]\n",
                       cal.label, cal.label, t.x(), t.y(), t.z(), R(0, 0), R(0, 1), R(0, 2), R(1, 0), R(1, 1),
                       R(1, 2), R(2, 0), R(2, 1), R(2, 2));
  }
  spdlog::info("wrote {}", (dir / "rig.yaml").string());
}

}  // namespace

int main(int argc, char** argv) {
  std::string recordDir, calibFile, outDir, rigDir, decode = "auto";
  std::vector<std::string> labels;
  std::vector<double> scales;
  std::size_t first = 0, count = 1, stride = 1;
  po::options_description desc("aimrec_extract options");
  desc.add_options()
      ("help,h", "show help")
      ("record", po::value(&recordDir)->required(), "record directory with Camera_*_meta.dat / _data.h264")
      ("calib", po::value(&calibFile), "aimprototype_config.zip or sensorconfig.yaml (default: zip next to the record)")
      ("labels", po::value(&labels)->multitoken(), "camera labels (default: all calibrated cameras)")
      ("out,o", po::value(&outDir), "output directory; without it only the summary is printed")
      ("first", po::value(&first), "first synced frame (index into the synced frame ids)")
      ("count", po::value(&count), "number of synced frames to write")
      ("stride", po::value(&stride), "synced frames between written frames")
      ("color", "write BGR instead of grey")
      ("scales", po::value(&scales)->multitoken(), "resize the images by these factors in turn (INTER_AREA)")
      ("decode", po::value(&decode), "decoding device: cpu, gpu or auto")
      ("dry-run", "decode, but write no images (decoding speed)")
      ("rig-out", po::value(&rigDir), "write a run_vo rig (rig.yaml, camera YAMLs, masks) of the opened cameras here");
  po::variables_map vm;
  try {
    po::store(po::parse_command_line(argc, argv, desc), vm);
    if (vm.count("help")) {
      std::cout << desc << '\n';
      return EXIT_SUCCESS;
    }
    po::notify(vm);
  } catch (const po::error& e) {
    spdlog::error("{}", e.what());
    std::cout << desc << '\n';
    return EXIT_FAILURE;
  }

  try {
    sdv::aimrec::setDecodeDevice(sdv::aimrec::parseDecodeDevice(decode));
    sdv::aimrec::Recording rec(recordDir, calibFile, labels);
    const auto& synced = rec.syncedFrameIds();
    spdlog::info("vehicle {}, {} cameras, {} synced frames", rec.vehicle(), rec.size(), synced.size());
    for (int c = 0; c < rec.size(); ++c) {
      const auto& cal = rec.calibration(c);
      const auto& meta = rec.stream(c).meta();
      const Eigen::Vector3d axis = cal.T_vehicle_camera.so3().matrix().col(2);
      spdlog::info("  {:20} {} {}x{} {:.1f} fps, {} frames (ids {}..{}), mask {}, optical axis ({:.3f}, {:.3f}, {:.3f})",
                   cal.label, cal.deviceId, meta.width, meta.height, meta.fps, meta.frames.size(),
                   meta.frames.front().frameId, meta.frames.back().frameId, cal.mask.empty() ? "no" : "yes",
                   axis.x(), axis.y(), axis.z());
    }
    if (!rigDir.empty()) writeRig(rec, rigDir);
    if (outDir.empty() || synced.empty()) return EXIT_SUCCESS;

    fs::create_directories(outDir);
    for (int c = 0; c < rec.size(); ++c)
      if (!rec.calibration(c).mask.empty())
        cv::imwrite((fs::path(outDir) / (rec.calibration(c).label + "_mask.png")).string(), rec.calibration(c).mask);

    const auto format = vm.count("color") ? sdv::aimrec::ImageFormat::Bgr : sdv::aimrec::ImageFormat::Gray;
    const bool write = !vm.count("dry-run");
    const auto tAll = std::chrono::steady_clock::now();
    std::size_t decoded = 0;
    for (std::size_t k = 0, i = first; k < count && i < synced.size(); ++k, i += stride, ++decoded) {
      const auto t0 = std::chrono::steady_clock::now();
      const std::vector<cv::Mat> images = rec.read(synced[i], format, scales);
      const double ms = std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
      for (int c = 0; c < rec.size() && write; ++c)
        cv::imwrite((fs::path(outDir) / fmt::format("{}_{:06}.png", rec.calibration(c).label, synced[i])).string(),
                    images[c]);
      if (write) spdlog::info("frame id {} (t = {} ns): decoded in {:.1f} ms", synced[i], rec.timestampNs(synced[i]), ms);
    }
    const double s = std::chrono::duration<double>(std::chrono::steady_clock::now() - tAll).count();
    spdlog::info("{} frames of {} cameras in {:.2f} s: {:.1f} frames/s", decoded, rec.size(), s, decoded / s);
  } catch (const std::exception& e) {
    spdlog::error("{}", e.what());
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
