// Writes a run_vo rig (rig.yaml plus one camera YAML per camera) from an aiMotive sensorconfig.yaml: EUCM cameras
// selected by label, videos found by device id, obstruction masks from the vehicle database.
#include <cstdlib>
#include <exception>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <numbers>
#include <string>
#include <vector>

#include <boost/program_options.hpp>
#include <Eigen/Geometry>
#include <spdlog/spdlog.h>
#include <yaml-cpp/yaml.h>

#include <sdv/aimrec/calibration.h>

namespace po = boost::program_options;
namespace fs = std::filesystem;

namespace {

fs::path findVideo(const fs::path& dir, const std::string& deviceId) {
  for (const auto& e : fs::directory_iterator(dir))
    if (e.is_regular_file() && e.path().extension() == ".h264" &&
        e.path().filename().string().find(deviceId) != std::string::npos)
      return e.path();
  throw std::runtime_error("no .h264 file with device id " + deviceId + " in " + dir.string());
}

}  // namespace

int main(int argc, char** argv) {
  std::string sensorconfigFile, videoDir, maskDir, outDir;
  std::vector<std::string> labels;
  po::options_description desc("rig_from_sensorconfig options");
  desc.add_options()
      ("help,h", "show help")
      ("sensorconfig", po::value(&sensorconfigFile)->required(), "sensorconfig.yaml")
      ("labels", po::value(&labels)->multitoken()->required(), "camera labels, e.g. F_FISHEYE_C M_FISHEYE_L")
      ("video-dir", po::value(&videoDir), "directory with <...>_<device id>_<...>.h264 (default: sensorconfig dir)")
      ("mask-dir", po::value(&maskDir), "base directory of obstruction_mask_file paths (default: sensorconfig dir)")
      ("out,o", po::value(&outDir)->required(), "output directory");
  try {
    po::variables_map vm;
    po::store(po::parse_command_line(argc, argv, desc), vm);
    if (vm.count("help")) {
      std::cout << desc << '\n';
      return EXIT_SUCCESS;
    }
    po::notify(vm);
  } catch (const po::error& e) {
    spdlog::error("{}", e.what());
    std::cout << desc << '\n';
    return EXIT_FAILURE;
  }

  try {
    const fs::path base = fs::absolute(sensorconfigFile).parent_path();
    const fs::path videos = videoDir.empty() ? base : fs::absolute(videoDir);
    const fs::path masks = maskDir.empty() ? base : fs::absolute(maskDir);
    const YAML::Node root = YAML::LoadFile(sensorconfigFile);
    fs::create_directories(outDir);

    std::ofstream rig(fs::path(outDir) / "rig.yaml");
    rig << "# Generated by rig_from_sensorconfig from " << fs::absolute(sensorconfigFile).generic_string() << "\n"
        << "cameras:\n";
    for (const auto& label : labels) {
      YAML::Node cam;
      bool found = false;
      for (YAML::Node s : root["sensors"])
        if (s["label"] && s["label"].as<std::string>() == label) cam.reset(s), found = true;
      if (!found) throw std::runtime_error("no sensor with label " + label);
      if (cam["model"].as<std::string>() != "eucm") throw std::runtime_error(label + ": only EUCM cameras supported");
      const auto res = cam["image_resolution_px"].as<std::vector<double>>();
      const auto pp = cam["principal_point_px"].as<std::vector<double>>();
      const auto f = cam["focal_length_px"].as<std::vector<double>>();
      const auto pos = cam["pos_meter"].as<std::vector<double>>();
      const auto ypr = cam["yaw_pitch_roll_deg"].as<std::vector<double>>();
      const std::string deviceId = cam["device_id"].as<std::string>();

      std::ofstream camFile(fs::path(outDir) / (label + ".yaml"));
      camFile << fmt::format("# {} ({}), EUCM from sensorconfig\nwidth: {}\nheight: {}\nfx: {}\nfy: {}\ncx: {}\ncy: {}\n"
                             "alpha: {}\nbeta: {}\n",
                             label, deviceId, res[0], res[1], f[0], f[1], pp[0], pp[1], cam["alpha"].as<double>(),
                             cam["beta"].as<double>());
      if (cam["custom_vars"] && cam["custom_vars"]["obstruction_mask_file"]) {
        const fs::path mask = masks / cam["custom_vars"]["obstruction_mask_file"].as<std::string>();
        if (!fs::exists(mask)) throw std::runtime_error("mask not found: " + mask.string());
        camFile << "mask: " << mask.generic_string() << "\n";
      }

      const Eigen::Matrix3d R =
          sdv::aimrec::vehicleFromCamera(Eigen::Vector3d::Zero(), {ypr.at(0), ypr.at(1), ypr.at(2)}).rotationMatrix();
      const Eigen::Vector3d axis = R.col(2);
      spdlog::info("{}: {} {}, optical axis in vehicle frame ({:.3f}, {:.3f}, {:.3f})", label, deviceId,
                   findVideo(videos, deviceId).filename().string(), axis.x(), axis.y(), axis.z());
      rig << fmt::format("  - name: {}\n    camera: {}.yaml\n    video: {}\n    T_body_camera:\n"
                         "      translation: [{}, {}, {}]\n      rotation_matrix: [{:.12f}, {:.12f}, {:.12f},\n"
                         "                        {:.12f}, {:.12f}, {:.12f},\n"
                         "                        {:.12f}, {:.12f}, {:.12f}]\n",
                         label, label, findVideo(videos, deviceId).generic_string(), pos[0], pos[1], pos[2], R(0, 0),
                         R(0, 1), R(0, 2), R(1, 0), R(1, 1), R(1, 2), R(2, 0), R(2, 1), R(2, 2));
    }
    spdlog::info("wrote {}", (fs::path(outDir) / "rig.yaml").string());
  } catch (const std::exception& e) {
    spdlog::error("{}", e.what());
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
